version: '3.8'

services:
  cypress:
    image: cypress/included:latest
    volumes:
      - ./cypress:/e2e/cypress
    working_dir: /e2e/cypress/e2e/k6-integration-tests
    command: ["npx", "cypress", "run"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpassword
      CYPRESS_TABLE_NAME: test_runs
    depends_on:
      - postgres
    networks:
      - test-network

  k6:
    image: loadimpact/k6
    volumes:
      - ./k6-scripts:/k6-scripts
    command: ["run", "/k6-scripts/api-test.js"]
    networks:
      - test-network

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - test-network

volumes:
  pgdata:

networks:
  test-network:
    driver: bridge