version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - test-network

  cypress:
    image: tulsanib/project_tulsanib_dbv1
    container_name: cypress_app
    command: ["npx", "cypress", "run"]
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
      CYPRESS_TABLE_NAME: test_runs
    depends_on:
      - postgres
    networks:
      - test-network

volumes:
  pgdata:

networks:
  test-network:
    driver: bridge