version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - test-network

  cypress:
    image: cypress/included:latest
    volumes:
      - ./cypress:/e2e/cypress
    working_dir: cypress/e2e/1-getting-started
    command: ["npx", "cypress", "run"]
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
      CYPRESS_TABLE_NAME: test_runs
    depends_on:
      - postgres
    networks:
      - test-network

volumes:
  pgdata:

networks:
  test-network:
    driver: bridge