version: '3.8'

services:
  cypress:
    image: cypress/included:latest
    volumes:
      - ./cypress:/e2e/cypress
    working_dir: /e2e/cypress/e2e/k6-integration-tests
    command: ["npx", "cypress", "run"]

  k6:
    image: loadimpact/k6
    volumes:
      - ./k6-scripts:/k6-scripts
    command: ["run", "/k6-scripts/api-test.js"]